export const FEATURED_COUNT = 1;
export const REGULAR_COUNT = 5;
export const TOTAL_PER_SECTION = FEATURED_COUNT + REGULAR_COUNT;
export const API_LIMIT_LOAD_MORE = 50;

export default {
  FEATURED_COUNT,
  REGULAR_COUNT,
  TOTAL_PER_SECTION,
  API_LIMIT_LOAD_MORE,
};
